"""your message

Revision ID: 2abbdde3c5fb
Revises: 29b9d73f6a25
Create Date: 2024-04-11 21:26:13.591609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abbdde3c5fb'
down_revision = '29b9d73f6a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
